app:
  frontend-url: "*"
  index-config-file: "index-config.json"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/${LOG_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 20

  kafka:
    bootstrap-servers: kafka:9093
    consumer:
      group-id: docker-spring-consumer-group # kafka consumer group id 임의 지정
  data:
    redis:
      host: redis
      port: 6379
  elasticsearch:
    uris: elasticsearch:9200